spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/news
    username: root
    password: ok


  mvc:
    view:
      prefix: /
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mapper/*.xml



